# Generated by Django 4.0.3 on 2024-04-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsmsApp', '0006_alter_laundry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundry',
            name='Address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
